### ISSUE TITLE
downloadPDF option in exporting does not work after upgrading from 4.1 to 5.4

### ISSUE THREAD

**Issue by prime19user** [highcharts/highcharts-angular#446]
> For general tech support, please see www.highcharts.com/support.
> Please report only issues about `highcharts-angular` wrapper or content of this repository.
> For general issues with Highcharts and TypeScript the correct repository to report such issues is [main Highcharts repository](https://github.com/highcharts/highcharts/issues).

### Describe the bug

A clear and concise description of what is wrong.

### Demo

Please provide live demo of the problem or provide any other way to recreate the problem.

#### Steps required to recreate the problem in the demo:

1. ...

### Setup used

- NodeJS version ...
- Angular version ...
- TypeScript version ...
  etc.

**Comment by prime19user** [comment]
<img width="467" height="491" alt="Image" src="https://github.com/user-attachments/assets/42b92c52-77e3-4017-8837-a2bd4aaf5010" />

Download PDF image of the chart does not work after upgrading from 4.1 to 5.4 Other download options work. Its just the downloadPdf option that does not work.

It was working with non ESM imports. 
Tried with following imports using the DEMO application
          import('highcharts/esm/modules/exporting'),
          import('highcharts/esm/modules/offline-exporting'),
          import('highcharts/esm/modules/export-data')

Please provide an example if this is not the correct approach.

Node version v22.13.1
Angular 20.3
highcharts 12.5
highcharts-angular 5.4

**Comment by karolkolodziej** [comment]
Hi @prime19user,

Unfortunately, I’m not able to recreate your issue. 
On my end, everything exports correctly—[see the live demo.](https://stackblitz.com/edit/stackblitz-starters-7atswfdz?file=src%2Fmain.ts)

If the issue persists, please modify the demo and provide steps on how to recreate.

**Comment by prime19user** [comment]
Thank you @karolkolodziej for your response. The live demo works as expected in stackblitz. However when I download the source and run it locally I get CORS errors 
Access to fetch at 'https://export-svg.highcharts.com/?v=12.5.0' from origin 'http://localhost:61199' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.

chunk-WDMUDEB6.js:49 
 POST https://export-svg.highcharts.com/?v=12.5.0 net::ERR_FAILED 403 (Forbidden)
chunk-WDMUDEB6.js:48 ERROR TypeError: Failed to fetch
    at chunk-WDMUDEB6.js:49:61
    at __async (chunk-WDMUDEB6.js:33:10)

In addition to import('highcharts/esm/modules/offline-exporting') do we need anything else to get this working. The downloadPNG works fine.

**Comment by karolkolodziej** [comment]
The CORS error means `offline-exporting` is falling back to the Highcharts export server instead of rendering locally.
Make sure the [exporting.local](https://api.highcharts.com/highcharts/exporting.local) is set to false if you want to export in on the client side.

I'm closing it for now since the original question has been answered. Feel free to reopen it or contact our [support](https://www.highcharts.com/support) for general Highcharts questions.
