### ISSUE TITLE
HStockTools not rendering the toolbar correctly

### ISSUE THREAD

**Issue by Rossco8** [highcharts/highcharts-angular#259]
### Describe the bug
Trying to use the Stock Toolbar in Angular 10 however it is not rendering, it appears as a dots and the buttons are not showing

### Demo
I can reproduce the problem by simply adding the following 2 lines of code to the example code from git@github.com:highcharts/highcharts-angular.git

**import HStockTools from "highcharts/modules/stock-tools";
HStockTools(Highcharts);**

When I view the sample code at 
https://stackblitz.com/edit/highcharts-angular-stock-gui?file=src%2Fapp%2Fapp.component.ts 
it all displays as expected in my browser, but on my Windows maching it does not display, screen shot attached. 
 
<img width="702" alt="Screen Shot 2021-01-10 at 3 56 59 pm" 
src="https://user-images.githubusercontent.com/44757794/104114847-02dc7b80-535d-11eb-8281-d5080dc9659b.png">

I have installed the package on my local machine
> **yarn add highcharts-angular**

### Setup used
 - NodeJS version v12
 - Angular version v10

**Comment by mateuszkornecki** [comment]
@Rossco8 Thanks for reporting the issue!

Could you tell me which browser you were using, and what was its version?

**Comment by Rossco8** [comment]
Hi,

I am on latest Chrome v 87.0.4280.141

Also, here are the exact steps to reproduce. My project is Angular 10 so I am using your demo code from tag 2.8.2 as the latest version looks like Angular 11?

> git clone --branch v2.8.2 git@github.com:highcharts/highcharts-angular.git

> Open VS Code (latest veresion) & open the project

From the Terminal
> npm install
> ng serve
 - Error, it does not compile, it complains about missing module "Cannot find module 'highcharts-angular' or its corresponding type declarations."

> So I added "highcharts-angular": "^2.4.0" to dependencies in package.json

> npm install
> ng serve

The demo works as expected and the page shows the examples

Now I want to see the Stock Toolbar

> I edit src\app\lazy-loading-chart\lazy-loading-chart.component.ts
to add the 2 lines of code for HStockTools, ensuring it is after HC_stock
import HStockTools from 'highcharts/modules/stock-tools';

HC_stock(Highcharts);
HStockTools(Highcharts);

The result is as per the screen shot, there are no errors in the Chrome console and none in the VS Code terminal

It is also worth mentioning I have tested another example I found on GitHub using Highcharts v7 and Angular v7 and the toolbar shows correctly
https://github.com/lironka/highcharts-angular-candlestick-depth/blob/master/package.json

**Comment by mateuszkornecki** [comment]
Thanks for the explanation!

We were trying to reproduce the issue however in our case everything is working correctly. Could you create a simple angular project and send it to us so we find what is not working or what could be done?

**Comment by Rossco8** [comment]
I have been able to work around the problem by including the 2 files gui.css and popup.css into my Angular project

So the problem is related to the stylesheets not being available at run time.

Can you please tell me what is the correct way to include the stylesheets?

**Comment by mateuszkornecki** [comment]
As you can see in the following demo: https://stackblitz.com/edit/highcharts-angular-stock-gui?file=src%2Fapp%2Fapp.component.ts there is no need to include any additional stylesheets to use highcharts unless you are using [`styledMode`](https://www.highcharts.com/docs/chart-design-and-style/style-by-css). 

Unfortunately, since I have no access to your project I am not able to give you a straightforward solution. If you want to add global styles this guide might help you: https://angular.io/guide/component-styles#external-and-global-style-files

**Comment by Rossco8** [comment]
Thanks for the sample code.

I was not including the FullScreen module because it was not compiling. But I can see it is needed.

The underlying error I am actually facing with Highcharts v8 then is that it will not compile due to the error

```
Error: node_modules/highcharts/modules/full-screen.d.ts:19:21 - error TS2304: Cannot find name 'Fullscreen'.
    
    19         fullscreen: Fullscreen;
```

If I edit the highcarts source code 
```
node_modules\highcharts\modules\full-screen.d.ts
```
And add an import for the missing class
```
import * as exporting from "./exporting"
```
It works as expected.

Why would I be facing such fundamental problems with the install & setup of Highcharts v8? Am I the only lucky one facing this problem?

**Comment by Rossco8** [comment]
Just to clarify, the example code you provided does not compile on my Windows machine, I needed to make the above changes to it

**Comment by mateuszkornecki** [comment]
@Rossco8 
Ok, I recreated the online demo as a local angular project and it looks like you are right - I was able to reproduce the same issue. Sorry that I missed it earlier. 

I will investigate it and post an update as fast as I can find any fix.

**Comment by mateuszkornecki** [comment]
@Rossco8 
**Stocktools issue:** 
According to the missing stock toolbar - that's my fault. You were right, stock tools require additional styles (`gui.css and popup.css`). The demo on the stackblitz that I was referring to, imported them in the `/styles.css` file: https://stackblitz.com/edit/highcharts-angular-stock-gui?file=src%2Fstyles.css. Sorry for misleading you!

**Fullscreen issue:**
 It seems that the Fullscreen module requires the Exporting module to be loaded. It was working correctly in the `8.0.0 < `version because that additional functionality that needs `ExportingModule` was introduced in the `8.0.1` version. 
This should definitely be better documented, I will report the issue on the `highcharts` repository.

```typescript
import HC_exporting from 'highcharts/modules/exporting';
import HFullScreen from 'highcharts/modules/full-screen';
HC_exporting(Highcharts);
HFullScreen(Highcharts);
```

I created a simple project for you, that should be working correctly regardless of your operation system:
https://github.com/mateuszkornecki/stockissue

Closing since the issue seems to be resolved, feel free to reopen the ticket if you will find any troubles with the stock tools.

**Comment by Rossco8** [comment]
Thanks @mateuszkornecki, good to know I am not going crazy. Including the exporting module fixed the compilation issue

There is still the question of the correct way to include the stylesheets. The only way we have, is to search the downloaded node_modules for the 2 files, then copy n paste the contents. But what if they change in a future version of Highcharts?

Is there perhapse a CDN address? or better still, enhancement request to include the stylesheets when we add Highcharts to the project.

**Comment by mateuszkornecki** [comment]
You don't need to use CDN to import them. Those files are available in the `highcharts` package.

**Live demo:** 
https://stackblitz.com/edit/highcharts-angular-stock-gui-9ijlzd?file=src%2Fstyles.scss

```sass
@import "highcharts/css/stocktools/gui.scss"
@import "highcharts/css/annotations/popup.scss"

```
