### ISSUE TITLE
Error: node_modules/highcharts-angular/lib/highcharts-chart.component.d.ts:22:21 - error TS2694: Namespace '"C:/Users/YML0443/workspace/ELVT/CustomerHub/node_modules/@angular/core/core"' has no exported member 'ɵɵFactoryDeclaration'

### ISSUE THREAD

**Issue by pranavkumar389** [highcharts/highcharts-angular#307]
Getting error while serving project `Error: node_modules/highcharts-angular/lib/highcharts-chart.component.d.ts:22:21 - error TS2694: Namespace '"C:/Users/YML0443/workspace/ELVT/CustomerHub/node_modules/@angular/core/core"' has no exported member 'ɵɵFactoryDeclaration'.`

Attaching the screen shot for your reference.

### Setup used
 - highcharts-angular version: "highcharts-angular": "^3.0.0",
 - Angular version:  "@angular/core": "~11.2.13",
 - TypeScript version: "typescript": "~4.0.2"

**Comment by karolkolodziej** [comment]
It looks like it might be related to the new version of that wrapper and a mismatch between some dependencies.

Could you please check if the demo works correctly with the `v2.10.0` of `highcharts-angular`?

**Comment by pranavkumar389** [comment]
Yes, it's successfully working with `v2.10.0`.

Can I get a fix for it? I will wait for a week.

**Comment by hakimio** [comment]
@karolkolodziej "partial" compilation shoudl work with both Angular v12 and v13. The issue is with all older versions of Angular.
You should update [General Prerequisites](https://github.com/highcharts/highcharts-angular#general-prerequisites) section of the README.

**Comment by iamprivateuser** [comment]
This (v2.10.0) is working for me on Angular 10 as well.

**Comment by notxesnad** [comment]
Thank you!!  Same issue - reverted from 3.0.0 to 2.10.0 and working now.

**Comment by soflyd** [comment]
Had the exact same issue, worked perfectly !
Thanks you so much @karolkolodziej

**Comment by adams-family** [comment]
Same issue here with v3 - any chance for a fix?

At the time of writing this comment, sadly following the tutorial for angular V14 and Highcharts (https://www.highcharts.com/blog/tutorials/highcharts-with-angular-v14/) reproduces the issue.

**Comment by karolkolodziej** [comment]
I have just created a fresh project with a standalone Highcharts component following the tutorial and everything is compiled correctly.
The only suggestion I might have is using `highcharts-angular` in version 2.10.0.

**Comment by karolkolodziej** [comment]
Yes, that is exactly what I did. My environment:
```
Angular CLI: 14.2.3
Node: 16.14.2
Package Manager: npm 8.5.0
```

**Comment by adams-family** [comment]
@karolkolodziej This is weird indeed, my configuration is:

```
Angular CLI: 14.2.3
Node: 16.13.1
Package Manager: npm 8.1.2
OS: linux x64
```

Did anyone who had this issue in the past with v3 report back that it has been fixed? Maybe it's somehow environment dependant...
