### ISSUE TITLE
Not compatible with Angular 5.2.10

### ISSUE THREAD

**Issue by tleveque23** [highcharts/highcharts-angular#25]
Just upgraded from Angular 5.2.9 to 5.2.10 and the compilation (AOT) is failing!
```
ERROR in Error during template compile of 'PlatformRef'
  Function calls are not supported in decorators but 'ɵmakeDecorator' was called in 'Injectable'
    'Injectable' calls 'ɵmakeDecorator'.
node_modules/highcharts-angular/node_modules/@angular/core/src/render3/ng_dev_mode.d.ts(9,11): error TS2451: Cannot redeclare block-scoped variable 'ngDevMode'.
node_modules/@angular/core/src/render3/ng_dev_mode.d.ts(9,11): error TS2451: Cannot redeclare block-scoped variable 'ngDevMode'.
```

**Comment by tleveque23** [comment]
Highcharts-Angular should be a real Angular module. We should have nothing to compile and nothing to add in the tsconfig file....

**Comment by KacperMadej** [comment]
We are working on updating the wrapper. Please check v5-dev brach to see it all works fine there. The branch is a next version candidate. https://github.com/highcharts/highcharts-angular/tree/v5-dev

The problem you are having is caused by dependencies from older version of Angular - it looks like Angular is not backward compatible with it self even after minor release or the problem was there from the beginning. Was the problem visible when you where using 5.2.9 version of Angular?

**Comment by tleveque23** [comment]
Like I said in the description, the bug started when I upgraded from 5.2.9 to 5.2.10. So yes it was working.
When do you think the new version will be release?

**Comment by KacperMadej** [comment]
@tleveque23 
It will be release within a week if it works well with 5.2.10+ version of Angular.
